### ISSUE TITLE
Unable to connect to QMP socket

### ISSUE THREAD

**Issue by fpatwa** [ALSchwalm/transient#58]
While using transient for spanning several instances 2 failed with the error below.
transient version: `transient==0.4`
The rest of the 10+ instances worked fine so this seems like a edge case issue:

```
time transient run -name 445554fa-773e-4a4e-a711-80e18fa36bb6 -image af4bc317-20ba-4fa3-bded-82ee224ac26c-0-XXXXX-test:0.3.2 -sshs -ssh-timeout 180 -image-frontend /home/transient/build/transient -image-backend /home/transient/build/transient -- -enable-kvm -m 1G -smp 2 -nographic -cpu max

Finished preparation. Starting virtual machine
Traceback (most recent call last):
  File "/home/transient/.local/bin/transient", line 11, in <module>
    sys.exit(main())
  File "/home/transient/.local/lib/python3.6/site-packages/transient/cli.py", line 205, in main
    returncode = trans.run()
  File "/home/transient/.local/lib/python3.6/site-packages/transient/transient.py", line 182, in run
    self.qemu_runner.qmp_client.connect()
  File "/home/transient/.local/lib/python3.6/site-packages/transient/qemu.py", line 79, in connect
    "Unable to connect to QMP socket at localhost:{}".format(self.port))
ConnectionRefusedError: Unable to connect to QMP socket at localhost:56107
Command exited with non-zero status 1
0.59user 0.09system 0:39.46elapsed 1%CPU (0avgtext+0avgdata 40960maxresident)k
12304inputs+8outputs (23major+17881minor)pagefaults 0swaps
```

**Comment by ALSchwalm** [comment]
Interesting. Can you try to reproduce this with verbose flags? Also what version of transient is this on?

**Comment by ALSchwalm** [comment]
Maybe 4 seconds isn't enough time for qemu to start up if you're under heavy load? That doesn't seem likely though

**Comment by fpatwa** [comment]
> Interesting. Can you try to reproduce this with verbose flags? Also what version of transient is this on?

Ok Just tried and I am able to reproduce it! 
Will get the logs and post it once the run is complete.

**Comment by fpatwa** [comment]
> > Interesting. Can you try to reproduce this with verbose flags? Also what version of transient is this on?
> 
> Ok Just tried and I am able to reproduce it!
> Will get the logs and post it once the run is complete.

Looks like the only additional log verbose gives is:
```
qemu-system-x86_64: terminating on signal 15 from pid 53985 (<unknown process>)
```

**Comment by fpatwa** [comment]
What I am running is tests that spin up multiple qemu instances in parallel. 
On a server with 8 cores, I am able to reproduce this issue quite reliably. 
On other servers with 12 cores I don't see this issue at all. There are a total of 12 testacases that are run and so on the server with 8 cores a single thread seems to spin up multiple instances 

On 8 core server:
```
======
Totals
======
Ran: 12 tests in 963.0587 sec.
 - Passed: 11
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 1
Sum of execute time for each test: 4319.5551 sec.
==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:16:03.057502
 - Worker 1 (1 tests) => 0:15:55.466999
 - Worker 2 (1 tests) => 0:07:41.067400
 - Worker 3 (1 tests) => 0:07:40.806742
 - Worker 4 (1 tests) => 0:06:59.738059
 - Worker 5 (2 tests) => 0:05:43.797996
 - Worker 6 (2 tests) => 0:05:13.401232
 - Worker 7 (3 tests) => 0:06:42.401885
```
On 12 core Server:
```
======
Totals
======
Ran: 12 tests in 331.1890 sec.
 - Passed: 12
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 1792.4113 sec.
==============
Worker Balance
==============
 - Worker 0 (1 tests) => 0:01:02.214161
 - Worker 1 (1 tests) => 0:05:31.051083
 - Worker 2 (1 tests) => 0:01:32.121706
 - Worker 3 (1 tests) => 0:04:54.342035
 - Worker 4 (1 tests) => 0:01:29.602532
 - Worker 5 (1 tests) => 0:01:45.114508
 - Worker 6 (1 tests) => 0:01:30.768548
 - Worker 7 (1 tests) => 0:01:30.948840
 - Worker 8 (1 tests) => 0:04:22.731220
 - Worker 9 (1 tests) => 0:01:43.917090
 - Worker 10 (1 tests) => 0:02:36.486557
 - Worker 11 (1 tests) => 0:01:53.112973
```

**Comment by ALSchwalm** [comment]
I believe this has now been resolved by the configurable qmp connection timeout.
