### ISSUE TITLE
Check format of `-image` argument to ensure it looks correct

### ISSUE THREAD

**Issue by pdietl** [ALSchwalm/transient#84]
Providing a bad argument to the `-image` argument should not break Transient.
Currently, if one forgets to add a version, i.e., a colon followed by a version, we get an error:

```
transient run -name provision_test -image ubuntu/focal64                                                                                                         
Unable to find image 'ubuntu/focal64' in backend                                       
Traceback (most recent call last):                                                     
  File "/home/pdietl/.local/bin/transient", line 8, in <module>                        
    sys.exit(main())                                                                   
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/cli.py", line 205, in main
    returncode = trans.run()                                                                                                                                                   
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 131, in run
    self.vm_images = self.__create_images(self.config.image)                                                                                                                   
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 35, in __create_images
    return [self.store.create_vm_image(image_name, self.config.name, idx)                                                                                                      
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 35, in <listcomp>
    return [self.store.create_vm_image(image_name, self.config.name, idx)                                                                                                      
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 335, in create_vm_image
    backing_image = self.retrieve_image(image_name)                                                                                                                            
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 329, in retrieve_image
    self.__download_vagrant_image(image_identifier, destination)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 217, in __download_vagrant_image
    box_name, version = image_identifier.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by ALSchwalm** [comment]
Note that this is a bit more complex than just validating the format. It is valid to have, for example, `-image myimage`, if that is an image name you have previously made via `-image myimage,http=https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-20150628_01.qcow2`. It is probably better to detect this particular failure and translate it to a more readable error:

```
No image named ubuntu/focal64 found in the backend, and no version provided so it cannot be downloaded
```
