### ISSUE TITLE
Fail gracefully when `libvirt` provider is not available

### ISSUE THREAD

**Issue by pdietl** [ALSchwalm/transient#85]
Attempting to use a vagrant box which doesn't have a libvirt provider currently fails ungracefully:

```
$ transient run -name provision_test -image ubuntu/focal64:v20200629.0.0
Unable to find image 'ubuntu/focal64:v20200629.0.0' in backend
Traceback (most recent call last):
  File "/home/pdietl/.local/bin/transient", line 8, in <module>
    sys.exit(main())
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/cli.py", line 205, in main
    returncode = trans.run()
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 131, in run
    self.vm_images = self.__create_images(self.config.image)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 35, in __create_images
    return [self.store.create_vm_image(image_name, self.config.name, idx)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/transient.py", line 35, in <listcomp>
    return [self.store.create_vm_image(image_name, self.config.name, idx)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 335, in create_vm_image
    backing_image = self.retrieve_image(image_name)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 329, in retrieve_image
    self.__download_vagrant_image(image_identifier, destination)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 230, in __download_vagrant_image
    box_url = self.__vagrant_box_url(version, box_info)
  File "/home/pdietl/.local/lib/python3.8/site-packages/transient/image.py", line 213, in __vagrant_box_url
    raise RuntimeError("No version '{}' available for {} with provider libvirt"
RuntimeError: No version '20200629.0.0' available for ubuntu/focal64 with provider libvirt
```

This should instead fail nicely.

**Comment by ALSchwalm** [comment]
Fixed in https://github.com/ALSchwalm/transient/commit/0bc7d7a8895ef0eaf7eecfeeaea956e20875f99f
